name: berg-app build and push to docker hub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        run: |
          docker build -t berg-app:test .

      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
        with:
          image: berg-app:test
          port: 3000

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: tag and push
        run: |
          docker tag berg-app:test ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:test
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:test