name: Berg App Docker Build and Push
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ajbergstedt
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ajbergstedt/bergapp:latest .

      - name: Start container
        run: |
          docker run -d -p 80:80 --name bergapp_container ajbergstedt/bergapp:latest
          sleep 5

      - name: Check if app is running
        run: |
          docker ps -a | grep bergapp_container

      - name: Debug container logs
        run: |
          docker logs bergapp_container

      - name: Test endpoint response
        run: |
          curl -s http://localhost:80/ || echo "Failed to connect to endpoint"

      - name: Install Test Dependencies
        run: |
          npm install axios chai mocha --save-dev

      - name: Run liatrio/github-actions/apprentice-action
        id: liatrio-tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Run Custom Minification Test
        if: success()
        run: |
          npx mocha minification.test.js --reporter spec
        id: minification-test

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ajbergstedt/bergapp:latest

      - name: Stop and remove container
        if: success()
        run: |
          docker stop bergapp_container || true
          docker rm bergapp_container || true