name: Berg App Docker Build and Push # Name of the workflow displayed in GitHub Actions

on:
  push:
    branches:
      - main


# SECTION: JOB DEFINITION
# This section defines a single job called 'build-and-push' that runs on an Ubuntu runner to
# build, test, and push a Docker image to Docker Hub.

jobs:
  build-and-push:
    runs-on: ubuntu-latest


# SUBSECTION: BUILD AND PUSH STEPS
# This subsection lists the steps to check out code, set up Docker, build a Docker image,
# test it locally, and push the image to Docker Hub.

    steps: 

    - name: Checkout code
      uses: actions/checkout@v3 # Uses the checkout action to clone the repo

    - name: Set up Docker Buildx # Step to configure Docker Buildx for advanced builds
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ajbergstedt
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: | 
        docker build -t ajbergstedt/bergapp:latest . 

    - name: Start container 
      run: | 
        docker run -d -p 80:80 --name bergapp ajbergstedt/bergapp:latest
        sleep 5 # Waits 5 seconds to allow the container to start

    - name: Check if app is running
      run: |
        docker ps -a | grep bergapp  # Lists containers and checks for 'bergapp'

    - name: Debug container logs
      run: | 
        docker logs bergapp 

    - name: Test endpoint response 
      run: | 
        curl -s http://localhost:80/ || echo "Failed to connect to endpoint" 

    - name: Install Test Dependencies 
      run: | 
        npm install axios@1.8.3 chai@4.3.6 mocha@10.7.3 --save-dev 

    - name: Run liatrio/github-actions/apprentice-action 
      id: liatrio-tests 
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91 

    - name: Debug Test File Existence 
      run: |
        ls -la .github/workflows/tests/minification.test.js || echo "File not found in .github/workflows/tests directory" 

    - name: Run Custom Minification Test 
      if: success() # Runs only if previous steps succeed
      run: | 
        npx mocha .github/workflows/tests/minification.test.js --reporter spec 
      id: minification-test 

    - name: Debug Image Before Push 
      run: | 
        docker images ajbergstedt/bergapp:latest 

    - name: Push Docker image to Docker Hub 
      if: success() # Runs only if previous steps succeed
      run: | 
        docker push ajbergstedt/bergapp:latest # Pushes the image to Docker Hub

    - name: Stop and remove container
      if: success() # Runs only if previous steps succeed
      run: | 
        docker stop bergapp || true 
        docker rm bergapp || true 
