name: berg-app build and push to docker hub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with Liatrio action
        uses: liatrio/github-actions/apprentice-action@master
        env:
          DOCKER_BUILDKIT: 1 # Enable BuildKit for better logging

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:latest