name: berg-app build and push to docker hub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t berg-app:test .

      - name: Run and test container
        run: |
          # Start container in background
          docker run -d -p 80:80 --name berg-app berg-app:test
          # Wait for app to start
          sleep 5
          # Install test dependencies
          npm install axios chai mocha -g
          # Run the test script
          curl -o test.js https://raw.githubusercontent.com/liatrio/apprentice-action/master/test.js
          mocha --reporter spec test.js
          # Stop container
          docker stop berg-app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/berg-app:latest